version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: managementDB
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: i2345678
    volumes:
      - pgdata:/var/lib/postgresql/data

  discovery-server:
    build:
      context: ./discovery-server
    container_name: discovery-server
    ports:
      - "8761:8761"

  users-service:
    build:
      context: ./users-service
    container_name: users-service
    ports:
      - "8083:8083"
    depends_on:
      - postgres
      - discovery-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/managementDB
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: i2345678
      SPRING_PROFILES_ACTIVE: docker

  employees-service:
    build:
      context: ./employees-service
    container_name: employees-service
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - discovery-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/managementDB
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: i2345678
      SPRING_PROFILES_ACTIVE: docker

  assets-service:
    build:
      context: ./assets-service
    container_name: assets-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - discovery-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/managementDB
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: i2345678
      SPRING_PROFILES_ACTIVE: docker

  asset-movements-service:
    build:
      context: ./asset-movements-service
    container_name: asset-movements-service
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - discovery-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/managementDB
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: i2345678
      SPRING_PROFILES_ACTIVE: docker

networks:
  default:
    name: spring-net


volumes:
  pgdata:
