services:
  db:
    container_name: management_system
    image: postgres:14.17
    restart: always
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ../db/initdb:/docker-entrypoint-initdb.d
      - pg_data_dev:/var/lib/postgresql/data

volumes:
  pg_data_dev:

