spring.application.name=discovery-server
server.port=8761

# Habilita la consola de Eureka y desactiva la auto-registro del mismo servidor
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka
