services:
  db:
    container_name: management_system_prod
    image: postgres:14.17
    restart: always
    env_file:
      - .env.prod
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ../db/initdb:/docker-entrypoint-initdb.d
      - pg_data_prod:/var/lib/postgresql/data

volumes:
    pg_data_prod: